image: node:16

stages:
  - build_cache
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - backend/node_modules/

cache-job:
  stage: build_cache
  script:
    - echo "Cache node_modules"
    - cd backend/
    - npm ci

backend-test-job:
  stage: test
  script:
    - echo "Running backend tests"

backend-build-job:
  stage: build
  script:
    - echo "Running backend build"
    - cd backend/
    - npm ci
    - npm run build

backend-build-docker-job:
  stage: build
  image: docker:19.03.1
  services:
    # To obtain a Docker daemon, request a Docker-in-Docker service
    - docker:19.03.1-dind
  tags:
    - csrunner1
  script:
    - cd backend/
    #- docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_BE_IMAGE_NAME:$CI_REGISTRY_BE_IMAGE_TAG" .
    - docker push "$CI_REGISTRY_BE_IMAGE_NAME:$CI_REGISTRY_BE_IMAGE_TAG"
  needs:
    - job: backend-build-job
  only:
    refs:
      - main

backend-deploy-job:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - csrunner1
  variables:
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - cd backend/
    - docker-compose -H $CI_DOCKER_HOST_DEV pull
    - docker-compose -H $CI_DOCKER_HOST_DEV up -d
  needs:
    - job: backend-build-docker-job
  only:
    refs:
      - main
